### ISSUE TITLE
add the missing features from the twitcher branch to agtv

### ISSUE THREAD

**Issue by scuq** [scuq/agtv#13]
- user stats (viewers, channel views)
- set broadcast title
- set game title
- game stats (viewers, channel views)
- global game stats

**Comment by torlenor** [comment]
I don't think that this should be in agtv. Maybe the game stats or a browser for games/channels but not "set broadcast title", "set game title". This should probably stay a separate tool for broadcasters. What do you think?

**Comment by torlenor** [comment]
Use the new TwitchApi to rebuild Twitcher.
