### ISSUE TITLE
Add support for choosing a video player

### ISSUE THREAD

**Issue by belldandu** [scuq/agtv#30]
Also if possible please add the ability to choose which player we want to use (not really all important but i like to use mpc-hc). After all not everyone uses (or likes) vlc.

**Comment by scuq** [comment]
if you don't want to install vlc, you could use the internal vlc, in the latest builds it should be working just fine, if you can figure out the right args, you could use another external player as well, the args and the player binary are configurable in the options.

**Comment by belldandu** [comment]
So if i were to give you configuration info for say mpc-hc would that info
be placed in the wiki somewhere so that other users may use mpc-hc with agtv

**Comment by scuq** [comment]
yes, of course, I could add some kind of "preset" selection for it
